/* Tests for scripts/model-history/validate.mjs. Run: node --test scripts/model-history/test/validate.test.mjs
   All data is FICTIONAL (fixtures/basic, generated by make-fixtures.mjs). Negative cases live in
   fixtures/validator-cases/cases.json (patches on an in-memory copy of basic) and, where real
   files are needed, in fixtures/validator-broken/. E18 and E29 need a repository layout and use
   temporary directories, so no design/ path or altered feed build is ever committed. */
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, readFileSync, copyFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { loadDataset, readJson, VOCAB, LIMITS, RE } from "../lib.mjs";
import { validate, CODES, maintenanceSummary } from "../validate.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const FIX = join(here, "fixtures");
const REPO = join(here, "..", "..", "..");
const SCRIPT = join(here, "..", "validate.mjs");
const NOW = "2026-10-10T00:00:00Z";   // after every fixture date, so W04/W10 stay quiet
const BASIC = loadDataset(join(FIX, "basic"));
const DATA_JSON = readJson(join(FIX, "basic", "data.json"));
const CASES = readJson(join(FIX, "validator-cases", "cases.json"));
const OPTS = { repoRoot: null, registry: null, dataJson: DATA_JSON, now: NOW, env: {} };

const errorCodes = f => [...new Set(f.filter(x => x.level === "error").map(x => x.code))].sort();
const show = f => f.map(x => `${x.code} ${x.level} ${x.file} ${x.path} ${x.message}`).join("\n");

/* ---------- Patch helpers for cases.json ---------- */
const segs = p => (Array.isArray(p) ? p : String(p).split(".")).map(s => (/^\d+$/.test(s) ? +s : s));
function walk(obj, path, create) {
  const s = segs(path);
  let o = obj;
  for (const k of s.slice(0, -1)) {
    if (o[k] === undefined || o[k] === null) { if (!create) return [undefined]; o[k] = {}; }
    o = o[k];
  }
  return [o, s[s.length - 1]];
}
function applyPatches(ds, patches) {
  const lists = { model: ds.models, org: ds.organizations, family: ds.families, source: ds.sources };
  for (const p of patches) {
    if (p.add) { lists[p.add].push(structuredClone(p.value)); continue; }
    let target;
    if (p.state) target = ds.state[p.state];
    else {
      const kind = Object.keys(lists).find(k => k in p);
      target = lists[kind].find(x => x.id === p[kind]);
      if (!target) throw new Error(`fixture has no ${kind} ${p[kind]}`);
    }
    for (const [path, v] of p.set || []) { const [o, k] = walk(target, path, true); o[k] = structuredClone(v); }
    for (const path of p.unset || []) { const [o, k] = walk(target, path, false); if (o) delete o[k]; }
    for (const [path, v] of p.push || []) { const [o, k] = walk(target, path, true); (o[k] = o[k] || []).push(structuredClone(v)); }
  }
  return ds;
}

/* ---------- The basic fixture ---------- */
test("basic fixture: zero errors, and only the expected W03 warnings (full repository checks)", () => {
  // repoRoot = the real repository: E18 compares the three id-function copies, the registry is
  // loaded from assets/registry.js, and the design guard looks for a design/ directory.
  const f = validate(structuredClone(BASIC), { repoRoot: REPO, dataJson: DATA_JSON, now: NOW, env: {} });
  assert.deepEqual(errorCodes(f), [], show(f));
  // Each W03 is an evidence situation the fixture contains on purpose (spec §16.4, AC-07).
  assert.deepEqual(f.map(x => `${x.code} ${x.file}`), [
    "W03 records/example-lab/orbit-0.json",          // primary source unavailable, no archive
    "W03 records/example-lab/orbit-2-vision.json",   // date via 2 secondary publishers; relation has only 1
    "W03 records/example-lab/orbit-3.json",          // one feature claim backed by a single blog post
    "W03 records/example-lab/orbit-lite-1.json",     // single secondary source, lifecycle unknown
    "W03 records/other-lab/nova-6.json"              // stub without dates
  ], show(f));
});

test("basic fixture without a repository root: E18 is skipped with a warning", () => {
  const f = validate(structuredClone(BASIC), OPTS);
  assert.deepEqual(errorCodes(f), []);
  assert.ok(f.some(x => x.code === "E18" && x.level === "warning" && /not compared/.test(x.message)), show(f));
});

test("findings are deterministic and have the documented shape", () => {
  const a = validate(structuredClone(BASIC), OPTS), b = validate(structuredClone(BASIC), OPTS);
  assert.deepEqual(a, b);
  for (const x of a) assert.deepEqual(Object.keys(x), ["code", "level", "file", "path", "message"]);
});

test("the validator never throws on malformed input", () => {
  const ds = structuredClone(BASIC);
  ds.models.push({ _file: "records/example-lab/junk.json", schemaVersion: 1, id: 42, organizations: [null, "x"], relations: "nope",
    variants: [null, 3], changes: {}, capabilities: { features: "x", parameters: 5 }, news: { include: "x" }, dates: { released: "2024" },
    lifecycle: { value: "available", sources: "src.example-lab.history" } });
  ds.organizations.push({ _file: "organizations.json", id: "junk-org", formerNames: "x", narrative: { chapters: {} } });
  ds.sources.push({ _file: "sources/shared.json", id: "src.shared.junk", publishedAt: "2024" });
  const f = validate(ds, OPTS);
  assert.ok(errorCodes(f).includes("E01"), show(f));
});

/* ---------- Cases ---------- */
for (const c of CASES.cases) {
  test(`${c.code}: ${c.name}`, () => {
    const ds = applyPatches(structuredClone(BASIC), c.patch);
    const f = validate(ds, { ...OPTS, registry: c.registry ? CASES.registry : null });
    assert.deepEqual(errorCodes(f), [...c.errors].sort(), show(f));
    for (const w of c.warnings || []) assert.ok(f.some(x => x.code === w && x.level === "warning"), `expected ${w}\n${show(f)}`);
    if (c.code.startsWith("E")) assert.ok(f.some(x => x.code === c.code && x.level === "error"), `expected ${c.code}\n${show(f)}`);
  });
}

test("E01/E15: invalid JSON, unknown schemaVersion and a record in the wrong folder (fixtures/validator-broken)", () => {
  const f = validate(loadDataset(join(FIX, "validator-broken")), OPTS);
  const errs = f.filter(x => x.level === "error").map(x => `${x.code} ${x.file} ${x.path}`);
  assert.deepEqual(errs, [
    "E01 records/test-lab/broken.json ",
    "E15 records/wrong-dir/model-a.json ",
    "E01 sources/test-lab.json schemaVersion"
  ], show(f));
});

test("E01: a missing data directory is an error", () => {
  const f = validate(loadDataset(join(FIX, "does-not-exist")), OPTS);
  assert.ok(f.some(x => x.code === "E01" && /data directory not found/.test(x.message)), show(f));
});

test("E25: without a registry, radarCompanyId checks become a warning", () => {
  const ds = applyPatches(structuredClone(BASIC), [{ org: "other-lab", set: [["coverage", "tracked"], ["radarCompanyId", "other-lab"]] }]);
  const f = validate(ds, OPTS);
  assert.deepEqual(errorCodes(f), [], show(f));
  assert.ok(f.some(x => x.code === "E25" && x.level === "warning" && /registry not available/.test(x.message)), show(f));
});

test("W10: a curator's local 'today' is never in the future, whatever the UTC time", () => {
  // 00:24 in Amsterdam (CEST) on 1 October 2026 is still 30 September in UTC; the fixture holds
  // many dates of 2026-10-01 (lastReviewedAt, lastCheckedAt), and none may warn.
  const early = { ...OPTS, now: "2026-09-30T22:24:00Z" };
  const f = validate(structuredClone(BASIC), early);
  assert.deepEqual(f.filter(x => x.code === "W10"), [], show(f));
  // A day that has not started anywhere on earth (UTC+14 is still on 1 October) does warn.
  const ds = applyPatches(structuredClone(BASIC), [{ source: "src.other-lab.site", set: [["lastCheckedAt", "2026-10-02"]] }]);
  assert.ok(validate(ds, early).some(x => x.code === "W10" && x.path.endsWith("lastCheckedAt")));
  // A timestamp is compared as an instant.
  const ts = applyPatches(structuredClone(BASIC), [{ source: "src.other-lab.site", set: [["lastCheckedAt", "2026-09-30T23:00:00Z"]] }]);
  assert.ok(validate(ts, early).some(x => x.code === "W10"));
});

test("W03: the model status comes from the known timeline date, not from an unknown released date", () => {
  const ds = applyPatches(structuredClone(BASIC), [{ model: "example-lab.orbit-2-5", set: [
    ["dates.announced", { value: "2024-11-20", sources: [{ id: "src.example-lab.orbit-2-5-launch" }] }],
    ["dates.released", { value: null, sources: [], note: "Release date not stated." }]] }]);
  const f = validate(ds, OPTS);
  assert.deepEqual(errorCodes(f), [], show(f));
  const w = f.find(x => x.code === "W03" && x.file === "records/example-lab/orbit-2-5.json");
  assert.ok(w, show(f));
  assert.match(w.message, /^evidence primary-source; insufficient evidence for dates\.released$/);
});

test("W08: neutral technical compounds (low-rank, best-effort) are not marketing language", () => {
  const w08 = text => validate(applyPatches(structuredClone(BASIC), [{ model: "example-lab.orbit-3", set: [["summary.text", text]] }]), OPTS)
    .filter(x => x.code === "W08" && x.path === "summary.text");
  assert.deepEqual(w08("Adds low-rank adapters and best-effort batch scheduling."), []);
  assert.deepEqual(w08("Supports rank-1 updates for LoRA (low-rank adaptation)."), []);
  assert.equal(w08("Ranked first on the leaderboard.").length, 1);
  assert.equal(w08("The best model of the family.").length, 1);
});

test("state/news-links.json: a complete, valid link passes", () => {
  const ds = applyPatches(structuredClone(BASIC), [{ state: "newsLinks", push: [["links", { modelId: "example-lab.orbit-2", variantId: "mini", postId: "abc123",
    link: "https://news.example.com/orbit-2-mini", title: "Orbit 2 Mini & friends", publishedAt: "2024-06-12T00:00:00Z", dateOnly: true, company: "Across AI",
    source: "Example News", method: "auto", alias: "orbit 2 mini", firstSeenAt: "2026-07-02T16:17:00Z", firstSeenIn: "a47100f" }]] }]);
  const f = validate(ds, OPTS);
  assert.deepEqual(errorCodes(f), [], show(f));
});

/* ---------- Repository guards (temporary repository layouts) ---------- */
function tempRepo(files) {
  const root = mkdtempSync(join(tmpdir(), "mh-validate-"));
  for (const [rel, text] of Object.entries(files)) { mkdirSync(dirname(join(root, rel)), { recursive: true }); writeFileSync(join(root, rel), text); }
  return root;
}

test("E18: an id-function copy that is not byte-identical fails; a missing copy only warns", () => {
  const feed = readFileSync(join(REPO, "scripts", "build-feed.mjs"), "utf8").replace("Math.imul(h1 ^ ch, 2654435761)", "Math.imul(h1 ^ ch, 2654435762)");
  const root = tempRepo({ "scripts/build-feed.mjs": feed });
  try {
    const f = validate(structuredClone(BASIC), { ...OPTS, repoRoot: root });
    assert.ok(f.some(x => x.code === "E18" && x.level === "error" && x.file === "scripts/build-feed.mjs"), show(f));
    assert.ok(f.some(x => x.code === "E18" && x.level === "warning" && x.file === "assets/app.js"), show(f));
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("E18: the real repository copies are byte-identical", () => {
  const root = tempRepo({});
  try {
    mkdirSync(join(root, "scripts"), { recursive: true }); mkdirSync(join(root, "assets"), { recursive: true });
    copyFileSync(join(REPO, "scripts", "build-feed.mjs"), join(root, "scripts", "build-feed.mjs"));
    // CRLF line endings (a Windows checkout) must not count as a difference.
    writeFileSync(join(root, "assets", "app.js"), readFileSync(join(REPO, "assets", "app.js"), "utf8").replace(/\r?\n/g, "\r\n"));
    const f = validate(structuredClone(BASIC), { ...OPTS, repoRoot: root });
    assert.ok(!f.some(x => x.code === "E18"), show(f));
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("E29: a top-level design/ directory fails on main and passes on a preview branch", () => {
  const root = tempRepo({ "design/model-history/index.html": "<!doctype html>" });
  try {
    const run = env => validate(structuredClone(BASIC), { ...OPTS, repoRoot: root, env }).filter(x => x.code === "E29");
    assert.equal(run({ GITHUB_REF: "refs/heads/main" }).length, 1);
    assert.equal(run({ GITHUB_BASE_REF: "main", GITHUB_REF: "refs/pull/7/merge" }).length, 1);
    assert.equal(run({ GITHUB_REF: "refs/heads/design/model-history" }).length, 0);
    assert.equal(run({}).length, 0);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

/* ---------- Coverage of the code list ---------- */
test("every code in CODES has at least one test", () => {
  const covered = new Set(CASES.cases.map(c => c.code));
  for (const c of CASES.cases) for (const w of c.warnings || []) covered.add(w);
  for (const code of ["E01", "E15", "E18", "E29", "W03"]) covered.add(code);   // tested above, outside cases.json
  const missing = Object.keys(CODES).filter(k => !covered.has(k));
  assert.deepEqual(missing, []);
  // Spec §26: E01–E28 plus the design guard E29; W06/W07 were dropped.
  assert.deepEqual(Object.keys(CODES).filter(k => k[0] === "E").length, 29);
  assert.ok(!("W06" in CODES) && !("W07" in CODES));
});

/* ---------- CLI ---------- */
const cli = (...args) => spawnSync(process.execPath, [SCRIPT, "--repo", REPO, ...args], { encoding: "utf8", cwd: REPO });

test("CLI --json on the basic fixture exits 0 and prints the findings", () => {
  const r = cli("--data", join(FIX, "basic") + "/", "--no-registry", "--json");
  assert.equal(r.status, 0, r.stderr);
  const f = JSON.parse(r.stdout);
  assert.ok(Array.isArray(f) && !f.some(x => x.level === "error"));
  assert.ok(f.every(x => ["code", "level", "file", "path", "message"].every(k => typeof x[k] === "string")));
});

test("CLI human output: one line per finding, a summary, exit 1 on errors", () => {
  const r = cli("--data", join(FIX, "validator-broken"), "--no-registry");
  assert.equal(r.status, 1);
  assert.match(r.stdout, /^E15 error {2}records\/wrong-dir\/model-a\.json {2}- {2}file must be records\/test-lab\/model-a\.json/m);
  assert.match(r.stdout, /^E01 error {2}sources\/test-lab\.json {2}schemaVersion {2}unknown schemaVersion 2/m);
  assert.match(r.stdout, /Model History validation: 3 errors, \d+ warnings? \(1 models, 1 organizations, 0 families, 1 sources\)/);
});

test("CLI rejects unknown arguments", () => {
  const r = cli("--nope");
  assert.equal(r.status, 2);
  assert.match(r.stderr, /unknown argument --nope/);
});

/* ---------- JSON Schemas stay in step with the validator (component rule C2 = C3) ---------- */
const SCHEMA_DIR = join(here, "..", "schema");
const schemas = Object.fromEntries(["organization", "family", "model", "source"].map(n => [n, readJson(join(SCHEMA_DIR, `${n}.schema.json`))]));

test("schemas are draft 2020-12 and every vocabulary enum equals lib.mjs VOCAB", () => {
  const seen = new Set();
  for (const [name, s] of Object.entries(schemas)) {
    assert.equal(s.$schema, "https://json-schema.org/draft/2020-12/schema", name);
    for (const [key, def] of Object.entries(s.$defs || {})) if (key in VOCAB) { assert.deepEqual(def.enum, VOCAB[key], `${name} $defs.${key}`); seen.add(key); }
  }
  assert.deepEqual(Object.keys(VOCAB).filter(k => !seen.has(k)), []);
});

test("schema id patterns and text limits equal lib.mjs", () => {
  const d = { ...schemas.model.$defs, ...schemas.organization.$defs, ...schemas.source.$defs };
  assert.equal(d.orgId.pattern, RE.org.source);
  assert.equal(d.scopedId.pattern, RE.scoped.source);
  assert.equal(d.sourceId.pattern, RE.source.source);
  assert.equal(d.slug.pattern, RE.slug.source);
  assert.equal(d.localId.pattern, RE.local.source);
  assert.equal(d.postId.pattern, RE.postId.source);
  const limits = { summary: "summaryText", change: "changeText", description: "descriptionText", chapterText: "chapterText",
    chapterTitle: "chapterTitle", name: "nameText", alias: "aliasText", note: "noteText", title: "titleText", label: "labelText" };
  for (const [k, def] of Object.entries(limits)) assert.equal(d[def].maxLength, LIMITS[k], def);
});

test("the job summary lists models with weak evidence (W03) and stale reviews (W04), capped", () => {
  const f = (code, file, message, level = "warning") => ({ code, level, file, path: "", message });
  const findings = [f("W03", "records/a/x.json", "evidence insufficient-evidence"), f("W04", "records/a/y.json", "last reviewed 2024-01-01, more than 12 months ago"),
    f("E04", "records/a/z.json", "unknown reference", "error"), ...Array.from({ length: 45 }, (_, i) => f("W03", `records/b/m${i}.json`, "evidence secondary-sources"))];
  const s = maintenanceSummary(findings);
  assert.match(s, /^### Model History: data maintenance\n\n1 error · 47 warnings \(E04 1, W03 46, W04 1\)/);
  assert.match(s, /#### Models with incomplete evidence \(46\)\n\n- `records\/a\/x\.json`: evidence insufficient-evidence/);
  assert.match(s, /- … and 6 more \(full list in the job log\)/);
  assert.match(s, /#### Records not reviewed for more than 12 months \(1\)\n\n- `records\/a\/y\.json`: last reviewed 2024-01-01/);
  assert.equal(maintenanceSummary([]), "### Model History: data maintenance\n\n0 errors · 0 warnings\n");
});